
// ACTIONS API FOR LOAD HOTELS
export const REQUEST_LOAD_HOTELS = 'REQUEST_LOAD_HOTELS'
export const SUCCESS_LOAD_HOTELS = 'SUCCESS_LOAD_HOTELS'
export const INVALID_LOAD_HOTELS = 'INVALID_LOAD_HOTELS'

// ACTIONS API FOR LOAD HOTEL
export const REQUEST_LOAD_HOTEL = 'REQUEST_LOAD_HOTEL'
export const SUCCESS_LOAD_HOTEL = 'SUCCESS_LOAD_HOTEL'
export const INVALID_LOAD_HOTEL = 'INVALID_LOAD_HOTEL'

//  ======== FILTERS =========
// ACTIONS LOAD REQUESTS COUNTRIES
export const REQUEST_LOAD_LIST_COUNTRIES = 'REQUEST_LOAD_LIST_COUNTRIES'
export const SUCCESS_LOAD_LIST_COUNTRIES = 'SUCCESS_LOAD_LIST_COUNTRIES'
export const INVALID_LOAD_LIST_COUNTRIES = 'INVALID_LOAD_LIST_COUNTRIES'

// ACTIONS LOAD REQUESTS CITIES
export const REQUEST_LOAD_LIST_CITIES = 'REQUEST_LOAD_LIST_CITIES'
export const SUCCESS_LOAD_LIST_CITIES = 'SUCCESS_LOAD_LIST_CITIES'
export const INVALID_LOAD_LIST_CITIES = 'INVALID_LOAD_LIST_CITIES'

// ACTIONS CHANGE FILTER
export const CHANGE_FILTER_COUNTRY = 'SELECT_FILTER_COUNTRY'
export const CHANGE_FILTER_CITY = 'SELECT_FILTER_CITY'
export const CHANGE_FILTER_COST = 'SEELCT_FILTER_COST'

export const CHANGE_SEARCH = 'CHANGE_SEARCH'
export const CHANGE_RATING = 'CHANGE_RATING'
export const RESET_FILTERS = 'RESET_FILTERS'

// ACTIONS CHANGE REQUESTS FILTERS
export const REQUEST_CHANGE_FILTERS = 'REQUEST_CHANGE_FILTERS'
export const SUCCESS_CHANGE_FILTERS = 'SUCCESS_CHANGE_FILTERS'
export const INVALID_CHANGE_FILTERS = 'INVALID_CHANGE_FILTERS'

export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const SUCCESS_SEARCH = 'SUCCESS_SEARCH'
export const INVALID_SEARCH = 'INVALID_SEARCH'

export const REQUEST_SEARCH_HOTELS = 'REQUEST_SEARCH_HOTELS'
export const SUCCESS_SEARCH_HOTELS = 'SUCCESS_SEARCH_HOTELS'
export const INVALID_SEARCH_HOTELS = 'INVALID_SEARCH_HOTELS'

// ACTIONS REVIEWS
export const REQUEST_LOAD_REVIEWS = 'REQUEST_LOAD_REVIEWS'
export const SUCCESS_LOAD_REVIEWS = 'SUCCESS_LOAD_REVIEWS'
export const INVALID_LOAD_REVIEWS = 'INVALID_LOAD_REVIEW'

export const REQUEST_CREATE_REVIEW = 'REQUEST_CREATE_REVIEW'
export const SUCCESS_CREATE_REVIEW = 'SUCCESS_CREATE_REVIEW'
export const INVALID_CREATE_REVIEW = 'INVALID_CREATE_REVIEW'
